
name: stockflow
description: A simple stock management app.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  share_plus: ^11.0.0

flutter:
  uses-material-design: true
